/**
 * Các toán tử so sánh
 * == => Bằng
 * != => không bằng
 * > => Lớn Hơn
 * < => Nhỏ hơn
 * >= Lớn hơn hoặc bằng
 * <= nhỏ hơn hoặc bằng
 */

//  == => (Bằng)
var a=4;
var b=4;

if(a==b){
    console.log('Điêu Kiện Đúng!');
}
else{
    console.log('Điêu Kiện Sai!')
}

//  != => không bằng
var c=5;
if(c!=b){
    console.log('Điêu Kiện Đúng!');
}
else{
    console.log('Điêu Kiện Sai!')
}

// > => Lớn Hơn
var d=2;
if(d>c){
    console.log('Điêu Kiện Đúng!');
}
else{
    console.log('Điêu Kiện Sai!')
}

// < => Nhỏ hơn
var e=1;
if(e<d){
    console.log('Điêu Kiện Đúng!');
}
else{
    console.log('Điêu Kiện Sai!')
}


/**
 * // >= Lớn hơn hoặc bằng
 */

var t=10;
if(t>=d){
    console.log('Điêu Kiện Đúng!');
}
else{
    console.log('Điêu Kiện Sai!')
}

/**
 * <= Nhỏ hơn hoặc bằng 
 */

 var k=100;
 if(k<=t){
     console.log('Điêu Kiện Đúng!');
 }
 else{
     console.log('Điêu Kiện Sai!')
 }